title: root
author: coffstation
email: HLN@thromail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hola, me dicen León y soy estudiante en informática! De vez en cuando escribo aquí en mi blog sobre la informática en general, el desarrollo web o quizás de video juegos. 
  Nací y me crie en chile, estudio en Duoc UC Puente alto - Santiago.

show_excerpts: false # set to true to show excerpts on the homepage

paginate: 7
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%d-%M-%dY"

  disqus:
    shortname:

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/Hleon_ing
      icon: twitter-square
      color: orange
  #    - url: https://bitbrain.itch.io
  #      icon: itch-io
  #      color: red
  #    - url: https://github.com/bitbrain
  #      icon: github-square
  #      color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging
# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: coffstation
